apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        version: 1
        editable: true
        isDefault: false
        jsonData:
          maxLines: 5000
          derivedFields:
            - name: "traceID"
              matcherRegex: "traceID=(\\w+)"
              url: "$${__value.raw}"
              datasourceUid: "tempo" 