apiVersion: v1
kind: Namespace
metadata:
  name: aiops
  labels:
    name: aiops
    purpose: anomaly-detection
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: observability 